### ISSUE TITLE
AppKey is not configured for service

### ISSUE THREAD

**Issue by wilsonssss** [betfair/stream-api-sample-code#5]
When we try to connect via unit test ClientTest#testStartStop, always response "AppKey is not configured for service",
API: stream-api-integration.betfair.com:443
Version：1.0-DELAY

LOG here: 
`[TestNG] Running:
  /Users/wilson/Library/Caches/IntelliJIdea2017.1/temp-testng-customsuite.xml
[main] INFO com.betfair.esa.client.auth.AppKeyAndSessionProvider - SSO Login - expiring session token now
[main] INFO com.betfair.esa.client.auth.AppKeyAndSessionProvider - SSO Login host=identitysso.betfair.com, appkey=YIzyW8PCO4xmRrV9, username=yqxnmmp@hotmail.com
[main] INFO com.betfair.esa.client.auth.AppKeyAndSessionProvider - identitysso.betfair.com: Response: com.betfair.esa.client.auth.AppKeyAndSessionProvider$SessionDetails@56cdfb3b
[main] INFO com.betfair.esa.client.Client - ESAClient: Opening socket to: stream-api-integration.betfair.com:443
[ESAClient] INFO com.betfair.esa.client.Client - ESAClient: Processing thread started
[ESAClient] INFO com.betfair.esa.client.protocol.RequestResponseProcessor - ESA->Client: {"op":"connection","connectionId":"050-010818025850-353593"}
[ESAClient] INFO com.betfair.esa.client.protocol.RequestResponseProcessor - ESAClient: Status changed STOPPED -> CONNECTED
[main] INFO com.betfair.esa.client.auth.AppKeyAndSessionProvider - SSO Login - session not expired - re-using
[main] INFO com.betfair.esa.client.protocol.RequestResponseProcessor - Client->ESA: {"op":"authentication","id":1,"appKey":"YIzyW8PCO4xmRrV9","session":"bMb44v+ueU/muxPxVzavbPLNQ0RE1MctSMH5bMsX4eo="}
[ESAClient] INFO com.betfair.esa.client.protocol.RequestResponseProcessor - ESA->Client: {"op":"status","id":1,"statusCode":"FAILURE","errorCode":"NOT_AUTHORIZED","errorMessage":"AppKey is not configured for service","connectionClosed":true,"connectionId":"050-010818025850-353593"}
[ESAClient] ERROR com.betfair.esa.client.Client - ESAClient: Error received processing socket - disconnecting:
java.io.IOException: Socket closed - EOF
	at com.betfair.esa.client.Client.run(Client.java:346)
	at java.lang.Thread.run(Thread.java:748)
[ESAClient] INFO com.betfair.esa.client.protocol.RequestResponseProcessor - ESAClient: Status changed CONNECTED -> STOPPED
[ESAClient] WARN com.betfair.esa.client.Client - ESAClient: Processing thread stopped

com.betfair.esa.client.protocol.ConnectionException: Future failed:

	at com.betfair.esa.client.Client.waitFor(Client.java:283)
	at com.betfair.esa.client.Client.authenticate(Client.java:244)
	at com.betfair.esa.client.Client.connectAndAuthenticate(Client.java:228)
	at com.betfair.esa.client.Client.start(Client.java:122)
	at com.betfair.esa.client.ClientTest.testStartStop(ClientTest.java:46)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:696)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:882)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1189)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:127)
Caused by: com.betfair.esa.client.protocol.ConnectionException: Connection reset - task cancelled
	at com.betfair.esa.client.protocol.RequestResponseProcessor.reset(RequestResponseProcessor.java:112)
	at com.betfair.esa.client.protocol.RequestResponseProcessor.stopped(RequestResponseProcessor.java:132)
	at com.betfair.esa.client.Client.disconnected(Client.java:387)
	at com.betfair.esa.client.Client.run(Client.java:360)
	at java.lang.Thread.run(Thread.java:748)

===============================================
Default Suite
Total tests run: 1, Failures: 1, Skips: 0
===============================================
`

**Comment by wilsonssss** [comment]
@mulveyj @bfapi pls help..

**Comment by bfapi** [comment]
Hi,

The App Key you are using is delayed and not currently authorised to use the streaming API.

Please contact the BDP team (bdp@betfair.com) to discuss opening up access.

Thanks
